---
- name: Configure Ansible Tower
  hosts: all
  become: yes
  become_user: root
  vars:
    tower_version: 3.8.2-1
  tasks: 
    - name: Ensure unzip and Ansible are installed
      dnf:
        name: 
          - unzip
          - ansible
        enablerepo: ansible-2.9-for-rhel-8-x86_64-rpms
        state: present 

    - name: Download the latest Tower
      unarchive:
        src: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ tower_version }}.tar.gz
        dest: /home/vagrant/
        remote_src: yes

    - name: Update Inventory passwords
      lineinfile:
        path: /home/vagrant/ansible-tower-setup-{{ tower_version }}/inventory
        regexp: "{{ item.original }}"
        line: "{{ item.new }}"
        state: present
      loop:
        - { original: "^admin_password", new: "admin_password='password'" }
        - { original: "^pg_password", new: "pg_password='password'" }

    - name: Run Ansible Tower Setup
      shell: ./setup.sh
      args:
        chdir: /home/vagrant/ansible-tower-setup-{{ tower_version }}
        creates: /etc/yum.repos.d/ansible-tower.repo
      async: 1400
      poll: 15